- name: Create Master Nodes
  ansible.builtin.import_playbook: create-masters.yaml
  tags:
    - create-masters

- name: Create Workers Nodes
  ansible.builtin.import_playbook: create-workers.yaml
  tags:
    - create-workers
