- ansible.builtin.import_playbook: create-ssh-key.yaml
  tags:
    - create-ssh-key

- ansible.builtin.import_playbook: prepare-images-bastion.yaml
  tags:
    - prepare-images-bastion

- ansible.builtin.import_playbook: prepare-images-utility.yaml
  tags:
    - prepare-images-utility

- ansible.builtin.import_playbook: create-ocp4-bm-nodes.yaml
  tags:
    - create-ocp4-bm-nodes

- ansible.builtin.import_playbook: prepare-utility.yaml
  tags:
    - prepare-utility

- ansible.builtin.import_playbook: prepare-bastion.yaml
  tags:
    - prepare-bastion

- ansible.builtin.import_playbook: configure-bastion.yaml
  tags:
    - configure-bastion

- ansible.builtin.import_playbook: install-ocp.yaml
  tags:
    - install-ocp

- ansible.builtin.import_playbook: configure-letsencrypt.yaml
  tags:
    - configure-letsencrypt
  when:
    - enable_ddns_duckdns|bool
    - enable_letsencrypt|bool

- ansible.builtin.import_playbook: scaledown-bastion.yaml
  tags:
    - scaledown-bastion
  when:
    - bastion.post_scaledown|bool
 
